version: '3.9'

services:
  backend:
    build: .
    image: wtkeqrf0/you_together-app
    volumes:
      - ./:/server/http
    ports:
      - "3000:3000"
    command: ["go","run","cmd/main/app.go"]
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  frontend:
    image: frkam/you-together-frontend
    ports:
      - "5173:5173"
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ubythfkbcbvec2
      - POSTGRES_DB=you_together
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
  proxy:
    image: frkam/you-together-proxy
    ports:
      - "80:80"
