version: '3.9'

services:
  backend:
    platform: linux/amd64
    image: wtkeqrf0/you-together-backend:main
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    platform: linux/amd64
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: "you-together"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    platform: linux/amd64
    image: redis:7.0.9-alpine3.17
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 8s
      timeout: 5s
      retries: 5




