version: '3.9'

services:
  backend:
    platform: linux/amd64
    image: wtkeqrf0/you-together-backend:latest
    volumes:
      - ./:/server/http
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    platform: linux/amd64
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres

  redis:
    platform: linux/amd64
    image: redis:7.0.9-alpine3.17
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  frontend:
    platform: linux/amd64
    image: frkam/you-together-frontend
    ports:
      - "5173:80"

  proxy:
    platform: linux/amd64
    image: frkam/you-together-proxy
    ports:
        - "80:80"


