version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: wtkeqrf0/you_together-app:latest
    volumes:
      - ./:/server/http
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_DB=you_together
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ubythfkbcbvec2
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 6

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
