openapi: 3.0.3
info:
  title: YouTogether API
  description: |-
    This is CRUD API documentation for you-together-online project.
    You can get more info about that project [here](https://github.com/youtogether-online)
  contact:
    email: matvey-sizov@mail.ru
  version: 1.0.0

externalDocs:
  description: Source code
  url: https://github.com/youtogether-online/backend

servers:
  - url: http://localhost:3000/api
    description: Backend local instance
  - url: https://youtogether.localhost/api
    description: Docker instance
  - url: https://youtogether.frkam.dev/
    description: Official website instance

tags:
  - name: Auth
    description: Interaction with the session
  - name: Email
    description: Send messages from application smtp email
  - name: User
    description: Get and update users
  - name: Room
    description: Any interaction with rooms

paths:
  /auth/session:
    get:
      tags: [ Auth ]
      summary: Returns authorized user session data
      description: Returns user session data from cookie session
      security:
        - cookieAuth: []
      responses:
        '200':
          $ref: '#/components/responses/SessionGetSuccess'
        '401':
          $ref: '#/components/responses/SessionGetUnathorized'
        '500':
          description: Server error

    delete:
      tags: [ Auth ]
      security:
        - cookieAuth: []
      summary: Deletes user session
      description: Deletes user session and clear user session cookie
      responses:
        '200':
          $ref: "#/components/responses/SessionDeleteSuccess"
        '500':
          description: Server error


  /auth/email:
    post:
      tags: [ Auth ]
      summary: Authorization via email
      description: Authorize user with code that previously was sent to email. If user with specified email does not exist, create new user. Can be used for sign-in and sign-up.
      requestBody:
        $ref: "#/components/requestBodies/AuthEmailPost"
      parameters:
        - in: header
          name: Accept-Language
          schema:
            type: string
            enum:
              - EN
              - RU
            example: RU
      responses:
        '201':
          $ref: "#/components/responses/AuthEmailSuccess"
        '400':
          $ref: "#/components/responses/AuthEmailFailed"
        '500':
          description: Server error

  /auth/password:
    post:
      tags: [ Auth ]
      summary: Authorization via email with password
      description: Authorize user with email and password. If user with specified email does not exist, create new user. Can be used for sign-in and sign-up.
      requestBody:
        $ref: "#/components/requestBodies/AuthPasswordPost"
      parameters:
        - in: header
          name: Accept-Language
          schema:
            type: string
            enum:
              - EN
              - RU
            example: RU
      responses:
        '201':
          $ref: '#/components/responses/AuthPasswordSuccess'
        '400':
          $ref: '#/components/responses/AuthPasswordFailed'
        '500':
          description: Server error

  /email/send-code:
    post:
      tags: [ Email ]
      summary: Send secret authorization code to specified email
      description: Generates 5-digit string, saves it and sends it to specified email
      requestBody:
        $ref: "#/components/requestBodies/EmailSendCodePost"
      responses:
        '200':
          $ref: '#/components/responses/EmailSendCodeSuccess'
        '500':
          description: Server error
  
  /user/{name}:
    get:
      tags: [ User ]
      summary: Get user main info by username
      description: Returns user's main data by username, if exist
      parameters:
        - $ref: "#/components/parameters/Name"
      responses:
        '200':
          $ref: '#/components/responses/UserGetByUsernameSuccess'
        '400':
          $ref: '#/components/responses/UserGetByUsernameFailed'
        '500':
          description: Server Error

  /user/check-name/{name}:
    get:
      tags: [ User ]
      summary: Check name on name already used
      description: Checks specified name on already exist
      parameters:
        - $ref: "#/components/parameters/Name"
      responses:
        '200':
          $ref: '#/components/responses/UserCheckNameGetByUsernameSuccess'
        '403':
          $ref: '#/components/responses/UserCheckNameGetByUsernameFailed'
        '500':
          description: Server Error

  /user:
    patch:
      tags: [ User ]
      summary: Update user's main data
      description: Updates some user's main data
      security:
        - cookieAuth: [ ]
      requestBody:
        $ref: "#/components/requestBodies/UserPatch"
      responses:
        '200':
          $ref: '#/components/responses/UserPatchSuccess'
        '400':
          $ref: '#/components/responses/UserPatchFailed'
        '401':
          $ref: '#/components/responses/UserPatchUnathorized'
        '500':
          description: Server error

  /user/password:
    patch:
      tags: [ User ]
      summary: Update user's password
      description: Updates user's password by email
      security:
        - cookieAuth: [ ]
      requestBody:
        $ref: "#/components/requestBodies/UserPasswordPatch"
      responses:
        '200':
          $ref: '#/components/responses/UserPasswordPatchSuccess'
        '400':
          $ref: '#/components/responses/UserPasswordPatchFailed'
        '401':
          $ref: '#/components/responses/UserPasswordPatchUnathorized'
        '500':
          description: Server error

  /user/email:
    patch:
      tags: [ User ]
      summary: Update user's email
      description: Updates user's email by password
      security:
        - cookieAuth: [ ]
      requestBody:
        $ref: "#/components/requestBodies/UserEmailPatch"
      responses:
        '200':
          $ref: '#/components/responses/UserEmailPatchSuccess'
        '400':
          $ref: '#/components/responses/UserEmailPatchFailed'
        '401':
          $ref: '#/components/responses/UserEmailPatchUnathorized'
        '500':
          description: Server error

  /user/name:
    patch:
      tags: [ User ]
      summary: Update user name
      description: Updates user name
      security:
        - cookieAuth: [ ]
      requestBody:
        $ref: "#/components/requestBodies/UserNamePatch"
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/UserNamePatchFailed'
        '401':
          $ref: '#/components/responses/UserNamePatchUnathorized'
        '500':
          description: Server Error

components:
  schemas:
    FirstName:
      type: string
      example: Bomb
      minLength: 3
      maxLength: 32
  
    LastName:
      type: string
      example: Hodovaniuk
      minLength: 3
      maxLength: 32

    Biography:
      type: string
      minLength: 1
      maxLength: 140
      example: 23 y.o designer from San Francisco
        
    Theme:
      type: string
      enum:
        - DARK
        - LIGHT
        - SYSTEM
      example: SYSTEM

    Language:
      type: string
      enum:
        - EN
        - RU
      example: RU

    Name:
      type: string
      writeOnly: true
      required:
        - name
      properties:
        username:
          type: string
          pattern: ^[a-zA-Z][a-zA-Z0-9_]{3,18}([a-zA-Z0-9])$
          example: user95
          minLength: 5
          maxLength: 20

    Email:
      type: string
      pattern: ^\S+@\S+\.\S+$
      example: example@example.com

    Password:
      type: string
      pattern: ^\P{Cc}\P{Cn}\P{Cs}$
      example: Bob2020

    Code:
      type: string
      minLength: 5
      maxLength: 5
      example: HI9I3

    Role:
      enum:
        - USER
        - ADMIN
      type: string
      example: USER

    User:
      type: object
      readOnly: true
      required:
        - name
        - role
      properties:
        name:
          $ref: "#/components/schemas/Name"
        firstName:
          $ref: "#/components/schemas/FirstName"
        lastName:
          $ref: "#/components/schemas/LastName"
        role: 
          $ref: "#/components/schemas/Role"
        biography:
          $ref: "#/components/schemas/Biography"

    Me:
      type: object
      readOnly: true
      required:
        - name
        - role
        - language
        - theme
        - isEmailVerified
      properties:
        name:
          $ref: "#/components/schemas/Name"
        firstName:
          $ref: "#/components/schemas/FirstName"
        lastName:
          $ref: "#/components/schemas/LastName"
        role:
          $ref: "#/components/schemas/Role"
        email:
          $ref: "#/components/schemas/Email"
        language:
          $ref: "#/components/schemas/Language"
        theme:
          $ref: "#/components/schemas/Theme"
        isEmailVerified:
          type: boolean
          example: false

    Error:
      type: object
      readOnly: true
      required:
        - code
      properties:
        description:
          type: string
          example: Wrong email or password
        advice:
          type: string
          example: You can still sign in by your email!
        fields:
          type: object
          additionalProperties:
            type: string
          example:
            email: email is not the correct email
            code: code must have a length of 5

  requestBodies:
    AuthEmailPost:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - code
            properties:
              email:
                $ref: "#/components/schemas/Email"
              code:
                $ref: "#/components/schemas/Code"
    
    AuthPasswordPost:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                $ref: "#/components/schemas/Email"
              password: 
                $ref: "#/components/schemas/Password"
    
    EmailSendCodePost:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
            properties:
              email: 
                $ref: "#/components/schemas/Email"

    UserPatch:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              firstName:
                $ref: "#/components/schemas/FirstName"
              lastName:
                $ref: "#/components/schemas/LastName"
              biography:
                $ref: "#/components/schemas/Biography"
              theme:
                $ref: "#/components/schemas/Theme"
              language:
                $ref: "#/components/schemas/Language"

    UserPasswordPatch:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - oldPassword
              - newPassword
            properties:
              oldPassword:
                $ref: "#/components/schemas/Password"
              newPassword:
                $ref: "#/components/schemas/Password"

    UserEmailPatch:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - newEmail
              - password
            properties:
              newEmail:
                $ref: "#/components/schemas/Email"
              password:
                $ref: "#/components/schemas/Password"

    UserNamePatch:
      required: true
      content:
        application/json:
          schema:
            type: object
            writeOnly: true
            required:
              - name
            properties:
              name:
                type: string
                pattern: ^[a-zA-Z][a-zA-Z0-9_]{3,18}([a-zA-Z0-9])$
                example: user95
                minLength: 5
                maxLength: 20

  parameters:
    Name:
      in: path
      description: Name
      name: name
      required: true
      schema:
        $ref: "#/components/schemas/Name"

  responses:
    SessionGetSuccess:
      description: Session exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Me'

    SessionGetUnathorized: 
      description: Failed to get session, maybe cookie is expired

    SessionDeleteSuccess:
      description: Session deleted

    AuthEmailSuccess:
      description: OK, user created
      headers:
        Set-Cookie:
          schema:
            type: string
            example: session_id=f82f97fd-9930-4133-a6a7-1bccb3b933b4; Path=/api; Domain=localhost; SameSite=None; Secure; HttpOnly;

    AuthEmailFailed: 
      description: Check or recover your credentials
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: email_already_exists
                    enum:
                      - email_already_exists
                      - invalid_validation
                      - code_invalid_or_expired
                      - email_already_activated
              - $ref: "#/components/schemas/Error"
            
      
    AuthPasswordSuccess:
      description: OK
      headers:
        Set-Cookie:
          schema:
            type: string
            example: session_id=f82f97fd-9930-4133-a6a7-1bccb3b933b4; Path=/api; Domain=localhost; SameSite=None; Secure; HttpOnly;
    
    AuthPasswordFailed:
      description: Check or recover your credentials
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: email_already_exists
                    enum:
                      - email_already_exists
                      - invalid_password
                      - invalid_validation
              - $ref: "#/components/schemas/Error"
    
    EmailSendCodeSuccess:
      description: Email was successfully sent

    UserGetByUsernameSuccess:
      description: User was successfully got
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"

    UserGetByUsernameFailed:
      description: Failed to get user
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: user_not_found
                enum:
                  - user_not_found
              - $ref: "#/components/schemas/Error"

    UserCheckNameGetByUsernameSuccess:
      description: This name isn't in use

    UserCheckNameGetByUsernameFailed:
      description: This name already in use

    UserPatchSuccess:
      description: User data updated

    UserPatchFailed:
      description: Failed to edit user data 
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: invalid_validation
                    enum:
                      - invalid_validation
              - $ref: "#/components/schemas/Error"

    UserPatchUnathorized:
      description: User unathorized to send this request

    UserPasswordPatchSuccess:
      description: Successfully edited user password

    UserPasswordPatchFailed:
      description: Failed to edit user password
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: incorrect_old_password
                    enum:
                      - invalid_validation
                      - incorrect_old_password
              - $ref: "#/components/schemas/Error"
    
    UserPasswordPatchUnathorized:
      description: User unathorized to send this request

    UserEmailPatchFailed:
      description: Failed to edit user email
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: email_already_exists
                    enum:
                      - invalid_validation
                      - code_invalid_or_expired
              - $ref: "#/components/schemas/Error"
    
    UserEmailPatchSuccess:
      description: Email was successfully changed

    UserEmailPatchUnathorized:
      description: User unathorized to send this request

    UserNamePatchSuccess:
      description: Name was successfully changed

    UserNamePatchFailed:
      description: Failed to edit user name
      content:
        application/json:
          schema:
            allOf:
              - required:
                  - "code"
                properties:
                  code:
                    type: object
                    example: user_name_already_taken
                    enum:
                      - invalid_validation
                      - user_name_already_taken
              - $ref: "#/components/schemas/Error"

    UserNamePatchUnathorized:
      description: User unathorized to send this request

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
