// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, Default: schema.Expr("nextval(pg_get_serial_sequence('users', 'id'))")},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Default: schema.Expr("'room' || currval(pg_get_serial_sequence('users', 'id'))")},
		{Name: "custom_name", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "owner_id", Type: field.TypeInt, Unique: true},
		{Name: "privacy", Type: field.TypeEnum, Enums: []string{"PRIVATE", "FRIENDS", "PUBLIC"}, Default: "PUBLIC"},
		{Name: "password_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "has_chat", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 140},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Default: schema.Expr("'user' || currval(pg_get_serial_sequence('users', 'id'))")},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "is_email_verified", Type: field.TypeBool, Default: false},
		{Name: "password_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "biography", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "role", Type: field.TypeString, Default: "USER"},
		{Name: "friends_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "language", Type: field.TypeString, Default: "EN"},
		{Name: "theme", Type: field.TypeString, Default: "SYSTEM"},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "sessions", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserRoomsColumns holds the columns for the "user_rooms" table.
	UserRoomsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "room_id", Type: field.TypeInt},
	}
	// UserRoomsTable holds the schema information for the "user_rooms" table.
	UserRoomsTable = &schema.Table{
		Name:       "user_rooms",
		Columns:    UserRoomsColumns,
		PrimaryKey: []*schema.Column{UserRoomsColumns[0], UserRoomsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_rooms_user_id",
				Columns:    []*schema.Column{UserRoomsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_rooms_room_id",
				Columns:    []*schema.Column{UserRoomsColumns[1]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RoomsTable,
		UsersTable,
		UserRoomsTable,
	}
)

func init() {
	UserRoomsTable.ForeignKeys[0].RefTable = UsersTable
	UserRoomsTable.ForeignKeys[1].RefTable = RoomsTable
}
