prod: false

session:
  refresh_duration_in_seconds: 2592000
  duration: 720h

listen:
  host: "127.0.0.1"
  port: 3000

db:
  postgres:
    host: "127.0.0.1"
    port: 5432
  redis:
    host: "127.0.0.1"
    port: 6379

email:
  from: "you-together@gmail.com"