// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/email/sign-in": {
            "post": {
                "description": "Compare the secret code with the previously sent codes. If at least one matches, create session of the user. If the user does not exist, create a new user",
                "tags": [
                    "Authorization"
                ],
                "summary": "Sign in by email",
                "parameters": [
                    {
                        "description": "User's email, secret code and device",
                        "name": "user_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EmailWithCode"
                        }
                    },
                    {
                        "enum": [
                            "EN",
                            "RU"
                        ],
                        "type": "string",
                        "description": "User's language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user's session"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/auth/password/sign-in": {
            "post": {
                "description": "Compare the user's password with an existing user's password. If it matches, create session of the user. If the user does not exist, create new user",
                "tags": [
                    "Authorization"
                ],
                "summary": "Sign in by password",
                "parameters": [
                    {
                        "description": "User's email, password",
                        "name": "EmailWithPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EmailWithPassword"
                        }
                    },
                    {
                        "enum": [
                            "EN",
                            "RU"
                        ],
                        "type": "string",
                        "description": "User's language",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user's session"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "404": {
                        "description": "Password is not registered for this account",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/email/send-code": {
            "post": {
                "description": "Send a secret 5-digit code to the specified email",
                "tags": [
                    "Email"
                ],
                "summary": "Send code to the user's email",
                "parameters": [
                    {
                        "description": "User's email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Email"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "403": {
                        "description": "Unable to connect to the specified email",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/session": {
            "get": {
                "description": "Returns detail information about me (session required)",
                "tags": [
                    "Sessions"
                ],
                "summary": "Get detail data about the user by session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dao.Me"
                        }
                    },
                    "401": {
                        "description": "User isn't logged in",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "404": {
                        "description": "User doesn't exist",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Make the user's session invalid (can accept cookie)",
                "tags": [
                    "Sessions"
                ],
                "summary": "Delete user's session",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user": {
            "patch": {
                "description": "Change user's main information (session required)",
                "tags": [
                    "User Update"
                ],
                "summary": "Update user's data",
                "parameters": [
                    {
                        "description": "New user data",
                        "name": "UpdateUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "401": {
                        "description": "User isn't logged in",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/user/check-name/{username}": {
            "get": {
                "description": "Status 200 if username not used or 403 if username is already used",
                "tags": [
                    "User Get"
                ],
                "summary": "Check username on exist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "name isn't used"
                    },
                    "400": {
                        "description": "Username is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "403": {
                        "description": "name already used"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/user/email": {
            "patch": {
                "description": "Change user's email by password (session required)",
                "tags": [
                    "User Update"
                ],
                "summary": "Update user's email",
                "parameters": [
                    {
                        "description": "user's password and new email",
                        "name": "UpdateEmail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "401": {
                        "description": "User isn't logged in",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/user/name": {
            "patch": {
                "description": "Change user's name (session required)",
                "tags": [
                    "User Update"
                ],
                "summary": "Update user's name",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "401": {
                        "description": "User isn't logged in",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "patch": {
                "description": "Change user's password by email (session required)",
                "tags": [
                    "User Update"
                ],
                "summary": "Update user's password",
                "parameters": [
                    {
                        "description": "user's email, code and new password",
                        "name": "UpdatePassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Data is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "401": {
                        "description": "User isn't logged in",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        },
        "/user/{username}": {
            "get": {
                "description": "Returns main information about the user",
                "tags": [
                    "User Get"
                ],
                "summary": "Get main data about the user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "main info",
                        "schema": {
                            "$ref": "#/definitions/dao.User"
                        }
                    },
                    "400": {
                        "description": "Param is not valid",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "404": {
                        "description": "User doesn't exist",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.MyError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dao.Me": {
            "description": "Detail information about the user",
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string",
                    "example": "I'd like to relax"
                },
                "email": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "Tele"
                },
                "friendsIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "bobba",
                        " imaxied"
                    ]
                },
                "isEmailVerified": {
                    "type": "boolean",
                    "example": true
                },
                "language": {
                    "type": "string",
                    "example": "RU"
                },
                "lastName": {
                    "type": "string",
                    "example": "phone"
                },
                "name": {
                    "type": "string",
                    "example": "bobbas"
                },
                "role": {
                    "type": "string",
                    "example": "USER"
                },
                "theme": {
                    "type": "string",
                    "example": "DARK"
                }
            }
        },
        "dao.User": {
            "description": "Main information about the user",
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string",
                    "example": "I'd like to relax"
                },
                "firstName": {
                    "type": "string",
                    "example": "Tele"
                },
                "friendsIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "tldtb",
                        "kigfv"
                    ]
                },
                "lastName": {
                    "type": "string",
                    "example": "phone"
                },
                "name": {
                    "type": "string",
                    "example": "bobbas"
                },
                "role": {
                    "type": "string",
                    "example": "USER"
                }
            }
        },
        "dto.Email": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                }
            }
        },
        "dto.EmailWithCode": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "I1ELB"
                },
                "email": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                },
                "theme": {
                    "type": "string",
                    "default": "SYSTEM",
                    "example": "DARK"
                }
            }
        },
        "dto.EmailWithPassword": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4,
                    "example": "onkr3451"
                },
                "theme": {
                    "type": "string",
                    "default": "SYSTEM",
                    "example": "DARK"
                }
            }
        },
        "dto.UpdateEmail": {
            "type": "object",
            "required": [
                "newEmail",
                "password"
            ],
            "properties": {
                "newEmail": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4,
                    "example": "onkr3451"
                }
            }
        },
        "dto.UpdatePassword": {
            "type": "object",
            "required": [
                "code",
                "email",
                "newPassword"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "I1ELB"
                },
                "email": {
                    "type": "string",
                    "example": "myemail@gmail.com"
                },
                "newPassword": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4,
                    "example": "onkr3451"
                }
            }
        },
        "dto.UpdateUser": {
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string",
                    "example": "I'd like to relax"
                },
                "firstName": {
                    "type": "string",
                    "maxLength": 30,
                    "example": "Tele"
                },
                "language": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 30,
                    "example": "phone"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "errs.MyError": {
            "description": "All native errors must be this type",
            "type": "object",
            "properties": {
                "advice": {
                    "type": "string",
                    "example": "Try to send request later"
                },
                "message": {
                    "type": "string",
                    "example": "Exception was occurred"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "You Together API",
	Description:      "It's an API interacting with You Together using Golang",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
