name: openapi-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/openapi-deploy.yml"
      - "docs/OpenAPI.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Build OpenAPI UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist
          spec-file: "docs/OpenAPI.yaml"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
